name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: format patch
      run: git format-patch -1
    - name: upload res
      uses: actions/upload-artifact@v2
      with:
          name: patches
          path: './0001*.patch'

