name: get commits action

on: [pull_request]

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "${{ steps.get-pr-commits.outputs.commits }}" > tmpfile_commit
        for commits in `cat tmpfile_commit | jq ".[].sha"`; do
          echo "$commits"
        done
        rm -f tmpfile_commit
