name: get commits action

on: [pull_request]

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
    - name: Get PR info
      id: 'get-pr-info'
      uses: Brymastr/pr-info-action@v1
      
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.get-pr-info.head_branch }}
        fetch-depth: ${{ steps.get-pr-info.head_branch }}
        
    - name: Get Commit Log
      run: |
        git log
