name: test action

on: [workflow_dispatch]

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: test action
    steps:
    - name: search coccinelle
      run: |
        uname -a
        cat /etc/lsb-release
        sudo apt-get search coccinelle
